# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g base-index 1

# DESIGN TWEAKS

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# copy mode
# setw -g mode-style 'fg=black bg=red bold'

# panes
# set -g pane-border-style 'fg=red'
# set -g pane-active-border-style 'fg=yellow'

# statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style bg="#1e1f1e",fg="red"
set -g status-left '[#{session_name}]'
set -g status-right '#H %Y-%m-%d %H:%M '
setw -g window-status-current-format ' #I:#[bold]#W#[nobold]#[fg=yellow]#F'
setw -g window-status-format ' #I:#[fg=red]#W#[fg=yellow]#F'

# setw -g window-status-bell-style 'fg=yellow bg=red bold'

# messages
# set -g message-style 'fg=yellow bg=red bold'

set -g default-terminal "linux"
