# vim:fileencoding=utf-8:foldmethod=marker

#: Fonts {{{

font_family      family='Iosevka Term Slab' style=Regular
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 12

#: }}}

#: Text cursor customization {{{

cursor_trail 1

cursor_trail_decay 0.1 0.4

#: }}}

#: Mouse {{{

detect_urls yes

#: }}}

#: Terminal bell {{{

enable_audio_bell no

command_on_bell "kitten notify $KITTY_CHILD_CMDLINE"

#: }}}

#: Window layout {{{

hide_window_decorations yes

#: }}}

#: Tab bar {{{

tab_bar_style fade

tab_bar_align right

tab_fade 0.5 0.75 1 1

tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{index}: {tab.last_focused_progress_percent}{tab.active_exe}"

active_tab_background   #FF46A2

inactive_tab_background #EEE

#: }}}

#: Color scheme {{{

# foreground #dddddd
# background #000000

#: The foreground and background colors.

background_opacity 0.5

background_blur 1

dynamic_background_opacity yes


#: }}}

#: Advanced {{{

allow_remote_control yes

listen_on unix:/tmp/kitty

#: }}}

#: OS specific tweaks {{{

linux_display_server wayland

#: }}}

#: Keyboard shortcuts {{{

map kitty_mod ctrl+shift

#: Tab management {{{

map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9

map alt+t launch --type=tab --cwd=current
map alt+w close_tab

#: }}}

#: Miscellaneous {{{

map kitty_mod+a>1 set_background_opacity 1
map kitty_mod+a>d set_background_opacity default
map kitty_mod+delete clear_terminal reset active

map kitty_mod+f2 edit_config_file
map kitty_mod+f5 load_config_file
map kitty_mod+f6 debug_config

#: }}}

#: }}}
