#!/bin/sh

echo "BOOSTRAP !!!"

yadm checkout /home/comet/

sudo pacman -S --needed git base-devel
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
cd ..
rm -rf yay

source ~/.bashrc

sudo pacman -S bluez bluez-utils nmap traceroute wget

yay -S lazygit less fastfetch neovim oh-my-posh nvm ripgrep fzf

yay -S hyprland bibata-cursor-theme-bin brightnessctl hyprpaper hyprpolkitagent luarocks mako noto-fonts nwg-look qt5-wayland qt5ct qt6-wayland qt6ct ttf-jetbrains-mono ttf-liberation waybar webkit2gtk wireplumber wl-clipboard xdg-desktop-portal-hyprland

yay -S kitty cava feishin spotify zen-browser-bin rofi

sudo pacman -S tree-sitter-cli python-gobject
