$font = monospace
# $wallpaper = $(swww query | sed -n 's/^.*image: //p')

general {
    hide_cursor = true
    ignore_empty_input = true
}

# uncomment to enable fingerprint authentication
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    #path = cmd[update 60] swww query | sed -n 's/^.*image: //p'
    # path = ~/.config/walls/monochrome-death.jpg
    # path = ~/.config/walls/autumn.png
    #path = ~/.config/walls/boat_abondoned.jpg
    path = ~/.config/current_wall
    blur_passes = 3
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgba(33ccffee) rgba(00ff99ee) 45deg
    check_color = rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 15

    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL

    # uncomment to use a letter instead of a dot to indicate the typed password
    dots_text_format = *
    dots_size = 0.3
    dots_spacing = 0.2

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    # position = -100, -100
    position = -20, 20
    halign = right
    valign = bottom
}

# Input Switcher
label {
    monitor =
    text = $LAYOUT[en, co]
    font_size = 20
    # onclick = hyprctl switchxkblayout all next
    onclick = niri msg action switch-layout "next"

    position = -420, 35
    halign = right
    valign = bottom
}

# TIME
label {
    monitor =
    text = <span font_features='zero'><tt>$TIME</tt></span> # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 90
    font_family = $font

    position = -30, 0
    halign = right
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] echo "<span font_features='zero,ss02'>$(date "+%A %d %B %Y")</span>" # update every 60 seconds
    font_size = 25
    font_family = $font

    position = -30, -150
    halign = right
    valign = top
}

# label {
#     monitor =
#     text = cmd[update:1000] python ~/Documents/programming/trellowidgets/fetcher.py
#     color = rgba(255, 255, 255, 1.0)
#     font_size = 22
#     font_family = $font
#     position = 20, -20
#     halign = left
#     valign = top
# }

label {
    monitor =
    text = cmd[update:10000] python ~/Documents/programming/taskwarriorwidgets/main.py
    # text = cmd[update:10000] python ~/docs/programming/taskwarriorwidgets/main.py
    color = rgba(255, 255, 255, 1.0)
    font_size = 22
    font_family = $font
    position = 20, -20
    halign = left
    valign = top
}

label {
    monitor =
    text = cmd[update:1000] python3 ~/.config/hypr/music.py
    color = rgba(255, 255, 255, 1.0)
    font_size = 22
    font_family = $font
    position = 20, 20
    halign = left
    valign = bottom
}
