general {
    lock_cmd = pidof hyprlock || ~/.config/hypr/hyprlocker       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session  # lock before suspend.
    # after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
    after_sleep_cmd = niri msg action power-on-monitors
}

# turn off keyboard backlight, comment out this section if you dont have a keyboard backlight.
listener { 
    timeout = 60                                           # 2.5min.
    #on-timeout = brightnessctl -sd rgb:kbd_backlight set 0 # turn off keyboard backlight.
    #on-resume = brightnessctl -rd rgb:kbd_backlight        # turn on keyboard backlight.
    on-timeout = brightnessctl -sd platform::kbd_backlight set 0 # turn off keyboard backlight.
    on-resume = brightnessctl -rd platform::kbd_backlight        # turn on keyboard backlight.
}

listener {
    timeout = 240                                 # 5min
    on-timeout = loginctl lock-session            # lock screen when timeout has passed
}

listener {
    timeout = 6000                                 # 30min
    on-timeout = power-off-monitors && systemctl suspend                # suspend pc
}
