# Recommended location for database
db_file            "~/.config/mpd/database"

# If running mpd using systemd, delete this line to log directly to systemd.
log_file           "syslog"

# The music directory is by default the XDG directory, uncomment to amend and choose a different directory
music_directory    "~/Music"

auto_update "yes"

audio_output {
    type "alsa"
    name "Main Output"
}

audio_output {
    type "fifo"
    name "Visualizer Loopback"
    path "/tmp/mpd.fifo"
}
